name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate with Salesforce using JWT
        run: |
          sf auth:jwt:grant --client-id 3MVG9YFqzc_KnL.xRNMyE_7Vv7Mm_SyxzN_8IjzQdB9AY4bNPaRJd6IH9qRuoYmG1pHht.XfV4GaNU9L2Z0tU \
                            --jwt-key-file <(echo "$JWT_PRIVATE_KEY") \
                            --username ehov1@gmail.com \
                            --instance-url https://login.salesforce.com
        env:
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}

      - name: Deploy metadata
        run: sf project deploy start --target-org ehov1@gmail.com
